import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Wrapper from "./wrapper/Wrapper";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Astrology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full bg-[#0D101D]`}
      >
        <Wrapper>
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
